[package]
name = "quick-sort-rust"
version = "0.1.0"
authors = ["Vijayaraagavan Manoharan <Vijayaraagavan.Manoharan@toyota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
